version: '2'
services:
    iplapplication-app:
        image: iplapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iplapplication-mysql:3306/iplapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://iplapplication-elasticsearch:9200
        ports:
            - 8080:8080
    iplapplication-mysql:
        extends:
            file: mysql.yml
            service: iplapplication-mysql
    iplapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iplapplication-elasticsearch
